### ISSUE TITLE
Kanban Board 

### ISSUE THREAD

**Issue by o-rashad** [Mosams/Yu-Gi-Oh_Cards_App#21]
**Board Link :** :ballot_box_with_check:  https://github.com/Mosams/Sam_Omar_Capstone/projects/2
**Team members :** :busts_in_silhouette:  2

**Comment by helman101** [comment]
# STATUS: APPROVED 🟢 🥳 

Hi @od-c0d3r & @Mosams 🥇 , 

### Congratulations!!! 🥳 🎉

You have successfully completed all the expectations for this project, there is nothing more to do here, now you can go on your way and keep improving your skills.

Cheers and Happy coding!👏👏👏

![gif](https://media.giphy.com/media/3o6fJ1BM7R2EBRDnxK/giphy.gif)

If anything is not 100% clear please leave your questions or comments in the PR thread, we will be glad to help you 😄.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by o-rashad** [comment]
Thanks for the review @helman101 :rocket:
