### ISSUE TITLE
Peer-to-peer feedback 23/12/2021

### ISSUE THREAD

**Issue by Debas-31** [Mosams/Yu-Gi-Oh_Cards_App#28]
Feedbacks, suggestions, improvements.

**Comment by AmaduKamara** [comment]
Hi @Mosams  and @od-c0d3r , your project is looking great.
I like the look and feel of your game app.

You guys are one step closer to finishing your tasks. Good luck in the rest of your milestones.

**Comment by o-rashad** [comment]
Thanks @Debas-31 for opening the issue :+1: , and @AmaduKamara for your feedback :100:
